// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaVotacion.API.Migrations
{
    [DbContext(typeof(SistemaVotacionAPIContext))]
    [Migration("20260223235605_v07")]
    partial class v07
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVotacion01.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("SistemaVotacion01.Padron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAcceso")
                        .HasColumnType("text");

                    b.Property<bool>("HaVotado")
                        .HasColumnType("boolean");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Padrones");
                });

            modelBuilder.Entity("SistemaVotacion01.PartidoPolitico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NOmbrePartido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("SimboloUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("PartidosPoliticos");
                });

            modelBuilder.Entity("SistemaVotacion01.ProcesoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreProceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion01.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaVotacion01.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cedula")
                        .HasColumnType("integer");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion01.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVoto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("SistemaVotacion01.lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreLista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartidoPoliticoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("PartidoPoliticoId");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("listas");
                });

            modelBuilder.Entity("SistemaVotacion01.Candidato", b =>
                {
                    b.HasOne("SistemaVotacion01.ProcesoElectoral", "ProcesosElectorales")
                        .WithMany("Candidatos")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion01.Padron", b =>
                {
                    b.HasOne("SistemaVotacion01.ProcesoElectoral", "ProcesosElectorales")
                        .WithMany("Padrones")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion01.Usuario", "Usuarios")
                        .WithMany("Padrones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcesosElectorales");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion01.PartidoPolitico", b =>
                {
                    b.HasOne("SistemaVotacion01.ProcesoElectoral", null)
                        .WithMany("PartidoPoliticos")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaVotacion01.Usuario", b =>
                {
                    b.HasOne("SistemaVotacion01.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaVotacion01.Voto", b =>
                {
                    b.HasOne("SistemaVotacion01.Candidato", "Candidatos")
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion01.ProcesoElectoral", "ProcesosElectorales")
                        .WithMany("Votos")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatos");

                    b.Navigation("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion01.lista", b =>
                {
                    b.HasOne("SistemaVotacion01.Candidato", "Candidatos")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion01.PartidoPolitico", "PartidosPoliticos")
                        .WithMany("Listas")
                        .HasForeignKey("PartidoPoliticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion01.ProcesoElectoral", "ProcesosElectorales")
                        .WithMany("Listas")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatos");

                    b.Navigation("PartidosPoliticos");

                    b.Navigation("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion01.Candidato", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaVotacion01.PartidoPolitico", b =>
                {
                    b.Navigation("Listas");
                });

            modelBuilder.Entity("SistemaVotacion01.ProcesoElectoral", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Listas");

                    b.Navigation("Padrones");

                    b.Navigation("PartidoPoliticos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaVotacion01.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion01.Usuario", b =>
                {
                    b.Navigation("Padrones");
                });
#pragma warning restore 612, 618
        }
    }
}
