// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaVotacion.API.Migrations
{
    [DbContext(typeof(SistemaVotacionAPIContext))]
    partial class SistemaVotacionAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaVotacion01.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProcesosElectoralesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesosElectoralesId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("SistemaVotacion01.Padron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAcceso")
                        .HasColumnType("text");

                    b.Property<bool>("HaVotado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdProceso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Padrones");
                });

            modelBuilder.Entity("SistemaVotacion01.PartidoPolitico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<string>("NOmbrePartido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("simboloUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("PartidosPoliticos");
                });

            modelBuilder.Entity("SistemaVotacion01.ProcesoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreProceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion01.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaVotacion01.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("cedula")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion01.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVoto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCandidato")
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesosElectoralesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ProcesosElectoralesId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("SistemaVotacion01.lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<int>("IdCandidato")
                        .HasColumnType("integer");

                    b.Property<int>("IdPartido")
                        .HasColumnType("integer");

                    b.Property<int>("IdProceso")
                        .HasColumnType("integer");

                    b.Property<string>("NombreLista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PartidosPoliticosId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("PartidosPoliticosId");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("listas");
                });

            modelBuilder.Entity("SistemaVotacion01.Candidato", b =>
                {
                    b.HasOne("SistemaVotacion01.ProcesoElectoral", "ProcesosElectorales")
                        .WithMany("Candidatos")
                        .HasForeignKey("ProcesosElectoralesId");

                    b.Navigation("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion01.Padron", b =>
                {
                    b.HasOne("SistemaVotacion01.ProcesoElectoral", "Proceso")
                        .WithMany("Padrones")
                        .HasForeignKey("IdProceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVotacion01.Usuario", "Usuarios")
                        .WithMany("Padrones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion01.PartidoPolitico", b =>
                {
                    b.HasOne("SistemaVotacion01.ProcesoElectoral", null)
                        .WithMany("Partidos")
                        .HasForeignKey("ProcesoElectoralId");
                });

            modelBuilder.Entity("SistemaVotacion01.Usuario", b =>
                {
                    b.HasOne("SistemaVotacion01.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaVotacion01.Voto", b =>
                {
                    b.HasOne("SistemaVotacion01.Candidato", "Candidato")
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId");

                    b.HasOne("SistemaVotacion01.ProcesoElectoral", "ProcesosElectorales")
                        .WithMany("Votos")
                        .HasForeignKey("ProcesosElectoralesId");

                    b.Navigation("Candidato");

                    b.Navigation("ProcesosElectorales");
                });

            modelBuilder.Entity("SistemaVotacion01.lista", b =>
                {
                    b.HasOne("SistemaVotacion01.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId");

                    b.HasOne("SistemaVotacion01.PartidoPolitico", "PartidosPoliticos")
                        .WithMany("Listas")
                        .HasForeignKey("PartidosPoliticosId");

                    b.HasOne("SistemaVotacion01.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany("Listas")
                        .HasForeignKey("ProcesoElectoralId");

                    b.Navigation("Candidato");

                    b.Navigation("PartidosPoliticos");

                    b.Navigation("ProcesoElectoral");
                });

            modelBuilder.Entity("SistemaVotacion01.Candidato", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaVotacion01.PartidoPolitico", b =>
                {
                    b.Navigation("Listas");
                });

            modelBuilder.Entity("SistemaVotacion01.ProcesoElectoral", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Listas");

                    b.Navigation("Padrones");

                    b.Navigation("Partidos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("SistemaVotacion01.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaVotacion01.Usuario", b =>
                {
                    b.Navigation("Padrones");
                });
#pragma warning restore 612, 618
        }
    }
}
